-- eDM Helper Campaign ID allocator
-- Safe to run with the existing campaign_counters and campaign_history tables.

create table if not exists public.campaign_id_allocations (
  id bigint generated by default as identity primary key,
  campaign_type text not null,
  sequence_number integer not null check (sequence_number between 1 and 9999),
  campaign_name text,
  monday_item_id text,
  monday_board_id text,
  source text not null default 'campaign-counter',
  status text not null default 'used'
    check (status in ('reserved', 'used', 'released')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Only one active allocation may use a number.
create unique index if not exists campaign_id_allocations_active_number_key
  on public.campaign_id_allocations (campaign_type, sequence_number)
  where status in ('reserved', 'used');

create index if not exists campaign_id_allocations_type_sequence_idx
  on public.campaign_id_allocations (campaign_type, sequence_number);

alter table public.campaign_id_allocations enable row level security;

drop policy if exists "campaign allocations are readable"
  on public.campaign_id_allocations;
create policy "campaign allocations are readable"
  on public.campaign_id_allocations
  for select
  using (true);

drop policy if exists "campaign allocations can be created"
  on public.campaign_id_allocations;
create policy "campaign allocations can be created"
  on public.campaign_id_allocations
  for insert
  with check (true);

drop policy if exists "campaign allocations can be updated"
  on public.campaign_id_allocations;
create policy "campaign allocations can be updated"
  on public.campaign_id_allocations
  for update
  using (true)
  with check (true);

-- Import every historical number that represents a used campaign ID.
insert into public.campaign_id_allocations (
  campaign_type,
  sequence_number,
  source,
  status,
  created_at,
  updated_at
)
select distinct on (history.campaign_type, history.value)
  history.campaign_type,
  history.value,
  'legacy-history',
  'used',
  history.created_at,
  history.created_at
from public.campaign_history history
where history.value between 1 and 9999
  and history.action not in ('reverted', 'released')
order by history.campaign_type, history.value, history.created_at
on conflict (campaign_type, sequence_number)
  where status in ('reserved', 'used')
  do nothing;

-- Also preserve the current counter when it is not present in history.
insert into public.campaign_id_allocations (
  campaign_type,
  sequence_number,
  campaign_name,
  source,
  status
)
select
  counter.campaign_type,
  counter.value,
  counter.name,
  'legacy-counter',
  'used'
from public.campaign_counters counter
where counter.value between 1 and 9999
on conflict (campaign_type, sequence_number)
  where status in ('reserved', 'used')
  do nothing;

create or replace function public.reserve_next_campaign_id(
  p_campaign_type text,
  p_floor integer default 1,
  p_campaign_name text default null,
  p_monday_item_id text default null,
  p_monday_board_id text default null,
  p_source text default 'campaign-counter'
)
returns public.campaign_id_allocations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sequence integer;
  v_allocation public.campaign_id_allocations;
begin
  if p_campaign_type is null or btrim(p_campaign_type) = '' then
    raise exception 'Campaign type is required';
  end if;

  if p_floor < 1 or p_floor > 9999 then
    raise exception 'Campaign sequence floor must be between 1 and 9999';
  end if;

  -- Serializes allocation per campaign type to prevent duplicate IDs.
  perform pg_advisory_xact_lock(
    hashtext('campaign-id:' || p_campaign_type)
  );

  select candidate
  into v_sequence
  from generate_series(p_floor, 9999) candidate
  where not exists (
    select 1
    from public.campaign_id_allocations allocation
    where allocation.campaign_type = p_campaign_type
      and allocation.sequence_number = candidate
      and allocation.status in ('reserved', 'used')
  )
  order by candidate
  limit 1;

  if v_sequence is null then
    raise exception 'No campaign IDs are available for %', p_campaign_type;
  end if;

  insert into public.campaign_id_allocations (
    campaign_type,
    sequence_number,
    campaign_name,
    monday_item_id,
    monday_board_id,
    source,
    status
  )
  values (
    p_campaign_type,
    v_sequence,
    nullif(btrim(p_campaign_name), ''),
    nullif(btrim(p_monday_item_id), ''),
    nullif(btrim(p_monday_board_id), ''),
    coalesce(nullif(btrim(p_source), ''), 'campaign-counter'),
    'used'
  )
  returning * into v_allocation;

  -- Keep the existing counter compatible with older UI/code.
  update public.campaign_counters
  set
    value = v_sequence,
    updated_at = now()
  where campaign_type = p_campaign_type;

  return v_allocation;
end;
$$;

revoke all on function public.reserve_next_campaign_id(
  text, integer, text, text, text, text
) from public;

grant execute on function public.reserve_next_campaign_id(
  text, integer, text, text, text, text
) to anon, authenticated;
